export enum OrderState {
    WAITING_CONFIRM = 'WAITING_CONFIRM',
    CONFIRMED = 'CONFIRMED',
    DELIVERING = 'DELIVERING',
    CANCELED = 'CANCELED',
    RECEIVED = 'RECEIVED',
    RETURNED = 'RETURNED'
}
