export enum PicklistType {
    GENDER = 'GENDER',
    PRODUCT_SIZE = 'PRODUCT_SIZE',
    PRODUCT_GENDER = 'PRODUCT_GENDER',
    PRODUCT_MOVENMENT = 'PRODUCT_MOVENMENT',
    PRODUCT_MARKET_SEGMENT = 'PRODUCT_MARKET_SEGMENT',
    PRODUCT_FEATURE = 'PRODUCT_FEATURE',
}
